spring.application.name=API
server.port=5555
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/flightsystemdb
spring.datasource.username=postgres
spring.datasource.password=123456



#JWT
jwt.secret=SZOgm+T/Wm9e1JjrL08d88FuLCkCJZQ7zBDl/Dho5RPo=
jwt.expiration=360000